dofile("Lua/GameConfig.txt")
dofile("Lua/CommonFun.txt")
dofile("Lua/Table/Table_Skill.txt")
dofile("Lua/Table/Table_Class.txt")
dofile("Lua/Table/Table_BuffStateOdds.txt")
dofile("Lua/Table/Table_Item.txt")
dofile("Lua/Table/Table_Guild_Faith.txt")
dofile("Lua/Table/Table_Map.txt")
dofile("Lua/Table/Table_Mail.txt")
dofile("Lua/oop.lua")
dofile("Lua/ServerLua.lua")
dofile("Lua/Item.lua")
dofile("Lua/Character.lua")
dofile("Lua/Reward.lua")
dofile("Lua/Log.lua")
dofile("Lua/ServerFunc.lua")
dofile("Lua/Activity.lua")

